NEPT-631: Added first version of validation
ec-europa/platform-dev pull request #1399
Opened 2017-04-28 11:24 UTC by imanoleguskiza

2017-05-02 15:34 UTC, gillesdeudon requested changes

2017-05-02 15:34 UTC, gillesdeudon commented on profiles/common/modules/features/cce_basic_config/cce_basic_config.module
> +      $errors[] = "The file's content type doesn't match the extension.";
I suggest as message: 

> The file's extension ("[extension]") does not match the file mime type ("[mimetype]")
where:

- [extension] is the extension retrieved from `$file->filename`;
- [mimetype] is the $real_mime value.

We should be as verbose as possible to inform the user about the error.

I think also that we should log the error (watchdog).

2017-05-02 15:34 UTC, gillesdeudon commented on profiles/common/modules/features/cce_basic_config/cce_basic_config.module
> +      $errors[] = "You don't have permissions to upload files to this folder.";
I suggest to mention that if the problem persists, the user must contact the administrator.

I think also that we should log the error (watchdog).

2019-01-18 13:28 UTC, Fefaine commented
PR added to the ticket. Currently blocked

2019-01-18 13:28 UTC, closed without merging