NEPT-1680: Made newsletters translatable.
ec-europa/platform-dev pull request #2218
Opened 2018-10-10 11:13 UTC by gillesdeudon

## NEPT-1680

### Description

Made newsletters translatable.

### Change log

- Changed: Made newsletters translatable.

2018-10-11 13:46 UTC, gillesdeudon reviewed
I did the PR but also the code review on the previous broken PR. It is ok for me.

2018-10-11 22:36 UTC, Fefaine requested changes

2018-10-11 22:36 UTC, Fefaine commented on profiles/common/modules/features/newsletters/newsletters.install
> +  variable_set('language_content_type_simplenews', ENTITY_TRANSLATION_ENABLED);
I don't like the idea of forcing ET at the install of the feature. What if someone wants to use it and does not want to use entity translation ? 42 sites (at least) have disabled ET

2018-10-30 08:34 UTC, aritomelo approved these changes
Looks ok for me. Next to +1

2018-11-06 09:48 UTC, ventzie555 approved these changes
Code looks good. I also tested it  and it looks like it the issue is fixed.

2018-11-06 10:31 UTC, Fefaine approved these changes

2018-11-06 10:32 UTC, merged