NEPT-570: Remove facetapi from profile dependencies
ec-europa/platform-dev pull request #2262
Opened 2018-11-07 12:47 UTC by ventzie555

## NEPT-570

### Description

Remove facetapi from profile dependencies

### Change log
- Changed:   profiles/multisite_drupal_communities/multisite_drupal_communities.info
- Changed:   profiles/multisite_drupal_standard/multisite_drupal_standard.info

2018-11-08 20:48 UTC, Fefaine requested changes
The feature multisite settings core adds the current_search block in the sidebar left of the search context.
I can't understand why. I suggest we move this block insertion inside the solr_config feature
THat's the only feature that requires facetapi, and current_search is a submodule of it.

2018-11-27 13:50 UTC, Fefaine approved these changes

2018-11-30 11:00 UTC, aritomelo approved these changes
After the bellows steps I give +1 to the PR.

- Confirmed that faceapi was installed/enabled by default
- Check if there is any remaning facetapi reference outside solr_config
- create a new instance based on branch nept-570-release-2.6
- Check if the module has been enabled by default, as expected NOT enabled.
- enabled the solr_config
- Recheck if the module has been enabled by enabling Solr config, and as expected It enables

2018-12-06 00:14 UTC, AlbaParrilla approved these changes
Ok for me 👍

2018-12-07 11:50 UTC, merged