NEPT-2315: Add patch for php7.2 warning
ec-europa/platform-dev pull request #2451
Opened 2019-03-26 13:36 UTC by tomv-be

## NEPT-2315

### Patch coung() notice on easy breadcrumb module

Applied patch for easy breadcrumb module:
https://www.drupal.org/project/easy_breadcrumb/issues/3043400

### Change log

- Changed: multisite_drupal_standard.make

2019-03-26 13:54 UTC, Fefaine requested changes
@tomv-be we add the NEPT issue and the drupal.org issue abobe each patch we add

2019-03-27 08:25 UTC, Fefaine submitted a review, later dismissed
OK thanks!

2019-03-28 13:29 UTC, Fefaine approved these changes
Ok for me

2019-03-29 12:16 UTC, drishu approved these changes

2019-04-09 12:54 UTC, merged