Nept 2414
ec-europa/platform-dev pull request #2481
Opened 2019-04-08 12:41 UTC by aritomelo

## NEPT-2414

### Description
Integrate EC Europa theme version 0.1.x in NextEuropa

2019-04-09 14:24 UTC, drupol requested changes

2019-04-09 14:24 UTC, drupol commented on build.xml
> +    <property file="build.properties.docker" />
This is out of scope.

2019-04-12 10:06 UTC, Fefaine requested changes
We now use the "semantic versioning" (or simili ;) ) so we base all our commits for next release to release-2.5.137 branch.
That's the branch that will be QAd and merged to 2.5 once the QA is validated.
Can you therefore rebase your PR to that branch? Thanks !

2019-04-12 10:19 UTC, drupol commented
Thanks @Fefaine , it's done.

2019-05-03 18:22 UTC, Fefaine approved these changes

2019-05-08 12:51 UTC, drupol approved these changes
@aritomelo great job ! Approving!

2019-05-08 12:51 UTC, merged