New docker-compose.yml for developing purposes
ec-europa/platform-dev pull request #2483
Opened 2019-04-09 12:11 UTC by jazio

## NEPT-

### Description

Added a docker-compose.yml for quickly building the platform on AWS or local pc without the need of LAMP.

### Change log

- Added: docker-compose.yml
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands
From root of the project.
docker-compose up -d

2019-04-09 12:21 UTC, drupol requested changes

2019-04-09 12:21 UTC, drupol commented on docker-compose.yml
> +      - ~/.composer/cache:/root/.composer/cache
This needs to be removed.

2019-04-09 12:21 UTC, drupol commented on docker-compose.yml
> +    image: percona/percona-server:5.6
5.6 or 5.7 ?

2019-04-15 07:51 UTC, jazio commented on docker-compose.yml
> +    image: percona/percona-server:5.6
Rather 5.6 [here](https://github.com/ec-europa/cloud9/search?q=percona&unscoped_q=percona).
I've push changes.

2019-06-07 09:24 UTC, Fefaine commented
See https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-2490 
The file is provided in C9, submit your change requests to https://github.com/ec-europa/cloud9/blob/master/salt/docker/files/docker-compose/docker-compose-all.yml

2019-06-07 09:24 UTC, closed without merging