NEPT-18: Move all subsites to NEXTEUROPA_METATAGS.
ec-europa/platform-dev pull request #2505
Opened 2019-04-24 07:09 UTC by drishu

## NEPT-18

### Description

Migrating multisite_metatags to nexteuropa_metatags. Enable nexteuropa_metatags by default. Uninstall multisite_metatags.

### Change log

- Added:
  - Hook to enable nexteuropa_metatags, migrate meta data and disable multisite_metatags.
  - README.md.
  - Variables nexteuropa_classification, nexteuropa_og_image, nexteuropa_creator, nexteuropa_reference.
  - File token.
  - nexteuropa_metatags.metatag.inc.
- Removed:
  - cce_basic_config_form_system_site_information_settings_alter().
  - nexteuropa_metatags.features.metatag.inc.

2019-07-17 11:47 UTC, Fefaine commented
I added some comments in the PR file.
I think we should also upgrade the metatags module.
I have this error after i ran the hook_update
Warning: Invalid argument supplied for foreach() in views_theme() (line 154 of /home/ec2-user/environment/platform-dev/profiles/multisite_drupal_standard/modules/contrib/views/views.module).

I could not identify where is comes from

2019-07-17 11:47 UTC, Fefaine requested changes

2019-07-17 11:47 UTC, Fefaine commented on profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.metatag.inc
> +  }
You are closing the condition too soon, we should only create the info tags ess gf entries if there is a taxonomy metatags_ess_gf

2019-07-17 11:47 UTC, Fefaine commented on profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.metatag.inc
> +    'description' => '',
we are adding a description here, but we add it again afterwards

2019-07-17 11:47 UTC, Fefaine commented on profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.metatag.inc
> +    'context' => array('global'),
This should move to $ne_defaults

2019-07-25 10:21 UTC, AlbaParrilla submitted a review, later dismissed

2019-08-01 08:16 UTC, Fefaine submitted a review, later dismissed

2019-08-08 13:10 UTC, AlbaParrilla approved these changes
Ok for me

2019-08-09 09:13 UTC, tomv-be approved these changes

2019-08-09 09:27 UTC, merged