NEPT-2424: Avoid using Nexteuropa Events and events core together.
ec-europa/platform-dev pull request #2543
Opened 2019-05-14 14:54 UTC by kameleon69

## NEPT-[Insert ticket number here]

### Description

Avoid using Nexteuropa Events and events core together.

### Change log

- Changed: events_core.install
- Changed : nexteuropa_event.install

2019-05-14 14:55 UTC, drupol requested changes

2019-05-14 14:55 UTC, drupol commented on profiles/common/modules/features/events/events_core/events_core.install
> +  return $requirements;
Missing blank line before return statement.

2019-05-14 14:55 UTC, drupol commented on profiles/common/modules/features/nexteuropa_event/nexteuropa_event.install
> +  return $requirements;
Same here.

2019-05-15 12:53 UTC, drishu approved these changes

2019-05-17 16:28 UTC, tomv-be approved these changes

2019-05-21 08:35 UTC, Fefaine commented
replaced with https://github.com/ec-europa/platform-dev/pull/2565

2019-05-21 08:35 UTC, closed without merging