NEPT-2228: Improve access_callback on og pages.
ec-europa/platform-dev pull request #2598
Opened 2019-06-13 17:24 UTC by drishu

## NEPT-2228

### Description

Add access control check to OG content pages.

### Change log

- Added: Add access control to menu entries like community/%group_name/%content_type
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

[Insert commands here]

2019-07-15 14:08 UTC, kameleon69 requested changes

2019-07-15 14:08 UTC, kameleon69 commented on profiles/common/modules/features/multisite_forum_community/multisite_forum_community.info
>  dependencies[] = multisite_forum_core
You shouldn't have these dependencies on this feature

2019-07-15 14:08 UTC, kameleon69 commented on profiles/common/modules/features/multisite_forum_community/multisite_forum_community.info
> +php = 5.2.4
we are on PHP 5.6

2019-07-15 14:08 UTC, kameleon69 commented on profiles/common/modules/features/multisite_forum_community/multisite_forum_community.install
> +  // Add multilinual forum to ogcontexte negocation (not.
typo here

2019-10-21 08:34 UTC, closed without merging

2019-10-21 08:34 UTC, Fefaine commented
SEE TICKET