NEPT-2709: Restrict access to user_administrator
ec-europa/platform-dev pull request #2809
Opened 2019-12-12 06:15 UTC by drishu

## NEPT-2709

### Description

Restrict access to user_administrator.

### Change log

- Added:
   - cce_basic_config_form_user_profile_form_alter()
   - cce_basic_config_query_alter

### Commands

drush cc all

### Checklist

- [x] Check if there are hook_updates and they are documented
- [ ] Add right labels to indicate in the devops ticket the commands to run
- [ ] Remove symlinks if it's a module removal

2019-12-12 16:16 UTC, tomv-be approved these changes

2019-12-16 13:05 UTC, Fefaine requested changes

2019-12-16 13:05 UTC, Fefaine commented on profiles/common/modules/features/cce_basic_config/cce_basic_config.module
> + */
We need some extra code comments here in order to remember later what we want to achieve

2019-12-16 13:05 UTC, Fefaine commented on profiles/common/modules/features/cce_basic_config/cce_basic_config.module
> +    drupal_goto('admin/people', [], 307);
Ok, but super admin should be able to change password or account details of that user_administrator.

2019-12-16 13:05 UTC, Fefaine commented on profiles/common/modules/features/cce_basic_config/cce_basic_config.module
> +  // Restrict access to user_administrator.
Here also i would add a condition to not add this for uid 1
Imagine some site have deleted the role user_administrator

2019-12-16 17:26 UTC, drishu commented on profiles/common/modules/features/cce_basic_config/cce_basic_config.module
> + */
done, bit more below

2019-12-16 17:27 UTC, drishu commented on profiles/common/modules/features/cce_basic_config/cce_basic_config.module
> +    drupal_goto('admin/people', [], 307);
fixed

2019-12-16 17:27 UTC, drishu commented on profiles/common/modules/features/cce_basic_config/cce_basic_config.module
> +  // Restrict access to user_administrator.
fixed

2020-01-24 09:11 UTC, merged