NEPT-2862 -- Allow 1FA authentication for whitelisted user roles.
ec-europa/platform-dev pull request #2924
Opened 2020-08-12 16:01 UTC by mehdi0712

## NEPT-2862

### Description

Allow 1FA authentication for whitelisted user roles.

### Change log

- Added: settings.php variable storing whitelisted roles, EcasDenieAuth class that centralize login authentication checks process, new warning page informing user about his account requirements in case of login denial.

- Changed: ecas_login_page() when a user is correctly logged in do not redirect him to a warning page, _ecas_warning_goto() logic moved, _ecas_session_end() logic moved

### Commands

### Checklist

- [ ] Check if there are hook_updates and they are documented
- [ ] Add right labels to indicate in the devops ticket the commands to run
- [ ] Remove symlinks if it's a module removal

2020-11-20 08:56 UTC, tomv-be requested changes
Functions very well. I left some nitpicky suggestions with regard to spelling.

2020-11-20 08:56 UTC, tomv-be commented on profiles/common/modules/custom/ecas/includes/ecas.inc
> +      Please reiterate your authentication by choosing a more secured authentication method (I.e. Mobile Phone + SMS).
```suggestion
      Please renew your authentication by choosing a more secure authentication method (e.g. Mobile Phone + SMS).
```
I wasn't sure about "reiterate", but "renew" is probably easier to understand regardless.

2020-11-20 08:56 UTC, tomv-be commented on profiles/common/modules/custom/ecas/includes/ecas.inc
> +      You just logged in using a one factor authentication method (I.e. Password) when your account requires a stronger authentication.
```suggestion
      You just logged in using a one-factor authentication method (i.e. Password), when your account requires a stronger authentication.
```

2020-11-20 08:56 UTC, tomv-be commented on profiles/common/modules/custom/ecas/includes/EcasDenieAuth.inc
> +class EcasDenieAuth {
In the class name, it should probably be either "deny" or "denied"? "Denie" is not a word, I think? But we'd need to make sure it's changed everywhere consistently, though. We don't wanna cause problems my trying to fix this. If too much trouble, leave it.

2020-11-21 08:45 UTC, Fefaine commented
Replaced by 
Management wants to restrict to 2.6
https://github.com/ec-europa/platform-dev/pull/2948

2020-11-21 08:45 UTC, closed without merging